---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 26.0.0
    values:
      - kraft:
          enabled: false
        broker:
          replicaCount: 5
        controller:
          replicaCount: 0
        image:
          registry: docker.io
          repository: bitnamilegacy/kafka
          tag: "3.5.2"
        auth:
          clientProtocol: sasl
          interBrokerProtocol: sasl
        sasl:
          enabledMechanisms: PLAIN
          interBrokerMechanism: PLAIN
          jaas:
            clientUsers:
              - kafka
              - admin
            clientPasswords:
              - kafka-prod-password
              - admin-prod-password
            interBrokerUser: admin
            interBrokerPassword: admin-prod-password
        zookeeper:
          enabled: true
          replicaCount: 1
          image:
            registry: docker.io
            repository: bitnamilegacy/zookeeper
            tag: "3.9.3-debian-12-r22"
          persistence:
            enabled: true
            size: 8Gi
        persistence:
          enabled: true
          size: 10Gi

  # Development Kafka: 1 брокер, PLAINTEXT без авторизации
  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: 26.0.0
    values:
      - kraft:
          enabled: false
        broker:
          replicaCount: 1
        controller:
          replicaCount: 0
        image:
          registry: docker.io
          repository: bitnamilegacy/kafka
        listeners:
          client:
            protocol: PLAINTEXT
          interBroker:
            protocol: PLAINTEXT
        zookeeper:
          enabled: true
          replicaCount: 1
          image:
            registry: docker.io
            repository: bitnamilegacy/zookeeper
            tag: "3.9.3-debian-12-r22"
          persistence:
            enabled: true
            size: 8Gi
        persistence:
          enabled: true
          size: 10Gi
