---
# StorageClass для CSI S3 (auto-provisioning: новый бакет или префикс создаётся автоматически).
# Provisioner и секрет должны совпадать с установленным CSI driver (csi-s3-secret в kube-system).
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-s3
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  # Чтобы использовать существующий бакет (префикс внутри него):
  # bucket: my-existing-bucket
  # https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
