---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  scope: Namespaced
  names:
    kind: MySQL
    plural: mysqls
    singular: mysql
    shortNames:
      - mysql
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - apiVersion
            - kind
            - metadata
            - spec
          properties:
            spec:
              type: object
              required:
                - image
                - database
                - password
                - storage_size
              properties:
                image:
                  type: string
                  minLength: 1
                  description: Docker image for MySQL Deployment
                database:
                  type: string
                  minLength: 1
                  description: Database name
                password:
                  type: string
                  minLength: 1
                  description: Database password
                storage_size:
                  type: string
                  minLength: 1
                  pattern: "^[0-9]+(Mi|Gi)$"
                  description: PVC size, for example 1Gi or 512Mi
      subresources:
        status: {}
