---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-custom
  namespace: mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-custom
rules:
  # Our CRD custom resources
  - apiGroups: ["otus.homework"]
    resources: ["mysqls"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["otus.homework"]
    resources: ["mysqls/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["otus.homework"]
    resources: ["mysqls/finalizers"]
    verbs: ["patch", "update"]

  # Children resources managed by operator
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

  # Events (optional but useful)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]

  # kopf may operate cluster-wide unless namespaces are explicitly configured
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  # kopf may watch CRDs for discovery/peering internals
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator-custom
subjects:
  - kind: ServiceAccount
    name: mysql-operator-custom
    namespace: mysql-operator
