---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  namespace: monitoring
  labels:
    app: nginx-prometheus-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
  selector:
    app: nginx-prometheus-exporter
