apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
  namespace: homework
data:
  file: |
    key1=value1
    key2=value2
    key3=value3
    database_host=localhost
    database_port=5432
    app_name=homework-app
    app_port=8000
